learning_templates/basic_app/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING

app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative_path_template, name='relative'),
    path('other/', views.other, name='other'),
    
]

learning_templates/urls.py
# from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context=context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative_path_template(request):
    return render(request, 'basic_app/relative_path_template.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

    <div class="container">
        <nav class="navbar navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
            <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
            <a class="navbar-brand" href="{% url 'basic_app:other' %}">Other</a>
          </div>
        </nav>
      </div>

    <div class="container">

        {% block body_block %}
        
        {% endblock body_block %}

    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <!--<h2>This is index.html page showing!</h2>-->
    <h1>{{ text|cut:"world" }}</h1>
    <h1>{{ number|add:"99" }}</h1>   


{% endblock body_block %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

    {% block body_block %} 
        <h1>WELCOME TO OTHER!</h1>
        <h2>This is example of body inheritance</h2>
    {% endblock body_block %}

learning_templates/templates/basic_app/relative_path_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO TEMPALTE</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}" >admin</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
</body>
</html>